// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package data

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AllClient is the client API for All service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AllClient interface {
	GetAll(ctx context.Context, in *AllRequest, opts ...grpc.CallOption) (*AllResponse, error)
}

type allClient struct {
	cc grpc.ClientConnInterface
}

func NewAllClient(cc grpc.ClientConnInterface) AllClient {
	return &allClient{cc}
}

func (c *allClient) GetAll(ctx context.Context, in *AllRequest, opts ...grpc.CallOption) (*AllResponse, error) {
	out := new(AllResponse)
	err := c.cc.Invoke(ctx, "/data.All/getAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AllServer is the server API for All service.
// All implementations should embed UnimplementedAllServer
// for forward compatibility
type AllServer interface {
	GetAll(context.Context, *AllRequest) (*AllResponse, error)
}

// UnimplementedAllServer should be embedded to have forward compatible implementations.
type UnimplementedAllServer struct {
}

func (UnimplementedAllServer) GetAll(context.Context, *AllRequest) (*AllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}

// UnsafeAllServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AllServer will
// result in compilation errors.
type UnsafeAllServer interface {
	mustEmbedUnimplementedAllServer()
}

func RegisterAllServer(s grpc.ServiceRegistrar, srv AllServer) {
	s.RegisterService(&All_ServiceDesc, srv)
}

func _All_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AllServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.All/getAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AllServer).GetAll(ctx, req.(*AllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// All_ServiceDesc is the grpc.ServiceDesc for All service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var All_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "data.All",
	HandlerType: (*AllServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getAll",
			Handler:    _All_GetAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data/data.proto",
}
